package Ventanas;

import ClasesAux.BookingHotel;
import ClasesAux.Cliente;
import ClasesAux.ClienteHistorico;
import ClasesAux.Habitacion;
import EDD.NodoListaSimple;
import ClasesAux.Reservacion;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author 58412
 */
public class Ventana1 extends javax.swing.JFrame {
    BookingHotel bookingHotel;
    /**
     * Creates new form Interfaz1
     */
    public Ventana1(BookingHotel bookingHotel) {
        initComponents();
        setTitle("Hotel Booking");
        setLocationRelativeTo(null);
        setResizable(false);
        this.bookingHotel = bookingHotel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        buscarCliente = new javax.swing.JButton();
        nombre = new javax.swing.JTextField();
        apellido = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        datosCliente = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        buscarReservacion = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        cedula = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        datosReservacion = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        mostrarClientes = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        numeroHabitacion = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        datosClientesHistoricos = new javax.swing.JTextArea();
        jPanel5 = new javax.swing.JPanel();
        cedulaReservacion = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        checkIn = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        datosCheckIn = new javax.swing.JTextArea();
        jPanel6 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        apellidoCheck = new javax.swing.JTextField();
        nombreCheck = new javax.swing.JTextField();
        CheckOut = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        datosCheckOut = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buscarCliente.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        buscarCliente.setText("Buscar Cliente");
        buscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarClienteActionPerformed(evt);
            }
        });
        jPanel2.add(buscarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 200, 50));

        nombre.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel2.add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 200, 40));

        apellido.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel2.add(apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 200, 40));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Nombre del Cliente");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 200, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Apellido del Cliente");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 200, 30));

        jScrollPane1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        datosCliente.setEditable(false);
        datosCliente.setColumns(20);
        datosCliente.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        datosCliente.setRows(5);
        jScrollPane1.setViewportView(datosCliente);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 50, 310, 310));

        jTabbedPane2.addTab("Búsqueda de Clientes", jPanel2);

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buscarReservacion.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        buscarReservacion.setText("Buscar Reservación");
        buscarReservacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarReservacionActionPerformed(evt);
            }
        });
        jPanel3.add(buscarReservacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 200, 50));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Cédula de Identidad");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 200, 30));

        cedula.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel3.add(cedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 200, 40));

        datosReservacion.setEditable(false);
        datosReservacion.setColumns(20);
        datosReservacion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        datosReservacion.setRows(5);
        jScrollPane2.setViewportView(datosReservacion);

        jPanel3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 50, 310, 310));

        jTabbedPane2.addTab("Búsqueda de Reservación", jPanel3);

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mostrarClientes.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        mostrarClientes.setText("Mostrar Clientes");
        mostrarClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarClientesActionPerformed(evt);
            }
        });
        jPanel4.add(mostrarClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 200, 50));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Número de Habitación");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 200, 30));

        numeroHabitacion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel4.add(numeroHabitacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 200, 40));

        datosClientesHistoricos.setEditable(false);
        datosClientesHistoricos.setColumns(20);
        datosClientesHistoricos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        datosClientesHistoricos.setRows(5);
        jScrollPane3.setViewportView(datosClientesHistoricos);

        jPanel4.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 50, 310, 310));

        jTabbedPane2.addTab("Historial de Habitación", jPanel4);

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cedulaReservacion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel5.add(cedulaReservacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 200, 40));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Cédula de Identidad");
        jPanel5.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 200, 30));

        checkIn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        checkIn.setText("Realizar Check-In");
        checkIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkInActionPerformed(evt);
            }
        });
        jPanel5.add(checkIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 200, 50));

        datosCheckIn.setEditable(false);
        datosCheckIn.setColumns(20);
        datosCheckIn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        datosCheckIn.setRows(5);
        jScrollPane4.setViewportView(datosCheckIn);

        jPanel5.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 50, 310, 310));

        jTabbedPane2.addTab("Check-In", jPanel5);

        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Nombre del Cliente");
        jPanel6.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 200, 30));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Apellido del Cliente");
        jPanel6.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 200, 30));

        apellidoCheck.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel6.add(apellidoCheck, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 200, 40));

        nombreCheck.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel6.add(nombreCheck, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 200, 40));

        CheckOut.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        CheckOut.setText("Realizar Check-Out");
        CheckOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckOutActionPerformed(evt);
            }
        });
        jPanel6.add(CheckOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 200, 50));

        datosCheckOut.setEditable(false);
        datosCheckOut.setColumns(20);
        datosCheckOut.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        datosCheckOut.setRows(5);
        jScrollPane5.setViewportView(datosCheckOut);

        jPanel6.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 50, 310, 310));

        jTabbedPane2.addTab("Check-Out", jPanel6);

        jPanel1.add(jTabbedPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, 440));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarClienteActionPerformed
        // TODO add your handling code here:
        String nombreC = nombre.getText().trim();
        String apellidoC = apellido.getText().trim();
        String info;
        if (bookingHotel.getHashEstado().buscar(apellidoC, nombreC) == null) {
            info = """
                   El cliente buscado no se encuentra
                   hospedado en el Hotel.
                   """;
        } else {
            info = bookingHotel.getHashEstado().buscar(apellidoC, nombreC).toString();
        }
        datosCliente.setText(info);
        nombre.setText("");
        apellido.setText("");
    }//GEN-LAST:event_buscarClienteActionPerformed

    private void buscarReservacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarReservacionActionPerformed
        // TODO add your handling code here:
        try {
            String texto = cedula.getText().trim();
            int cedulaC = Integer.parseInt(texto);
            String info;
            if (bookingHotel.getArbolReservaciones().buscarReservacion(cedulaC) == null) {
                info = "La reservación no existe.";
            } else {
                info = bookingHotel.getArbolReservaciones().buscarReservacion(cedulaC).toString();
            }
            datosReservacion.setText(info);
            cedula.setText("");
        } catch (NumberFormatException e) {
            datosReservacion.setText("Por favor, ingrese un valor válido.");
            cedula.setText("");
        }

    
    }//GEN-LAST:event_buscarReservacionActionPerformed

    private void checkInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkInActionPerformed
        // TODO add your handling code here:
        try {
            String texto = cedulaReservacion.getText().trim();
            int cedulaReservacionC = Integer.parseInt(texto);
            String info;
            Habitacion habitacion;
            int habitacionAsignada = -1;
            if (bookingHotel.getArbolReservaciones().buscarReservacion(cedulaReservacionC) == null) {
                info = "La reservación no existe.";
            } else {
                Reservacion reserva = bookingHotel.getArbolReservaciones().buscarReservacion(cedulaReservacionC);
                NodoListaSimple aux = bookingHotel.getHabitacionesDisponibles().getpFirst();
                while (aux != null) {
                    habitacion = bookingHotel.getArbolHabitaciones().buscarHabitacion((int)aux.getData());
                    if (habitacion.getTipo().equals(reserva.getTipoHabitacion())) {
                        habitacionAsignada = (int)aux.getData();
                        bookingHotel.getHabitacionesDisponibles().eliminar(aux.getData());
                        break;
                    }
                    aux = aux.getpNext();
                }
                if (habitacionAsignada == -1) {
                    info = "No hay habitaciones disponibles en este momento.";
                } else {
                    Cliente cliente = new Cliente(reserva.getPrimerNombre(), reserva.getSegundoNombre(), reserva.getEmail(), reserva.getGenero(), reserva.getCelular(), reserva.getLlegada(), habitacionAsignada);
                    bookingHotel.getHashEstado().insertar(cliente);
                    bookingHotel.getArbolReservaciones().eliminarReservacion(reserva.getCedula());
                    info = "Se le ha asignado la habitación " + habitacionAsignada + ".\nSus datos a continuación:\n\n" + cliente.toString();
                    
                }
                
            }
            datosCheckIn.setText(info);
            cedulaReservacion.setText("");
        } catch (NumberFormatException e) {
            datosCheckIn.setText("Por favor, ingrese un valor válido.");
            cedulaReservacion.setText("");
        }
        
        
    }//GEN-LAST:event_checkInActionPerformed

    private void mostrarClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarClientesActionPerformed
        // TODO add your handling code here:
        try {
            String texto = numeroHabitacion.getText().trim();
            int numeroHabitacionC = Integer.parseInt(texto);
            String info;
            if (bookingHotel.getArbolHabitaciones().buscarHabitacion(numeroHabitacionC) == null) {
                info = "La habitación no existe.";
            } else {
                if (bookingHotel.getArbolHabitaciones().buscarHabitacion(numeroHabitacionC).getClientes() == null) {
                    info = "Nadie se ha hospedado en esta habitación.";
                } else {
                    info = bookingHotel.getArbolHabitaciones().buscarHabitacion(numeroHabitacionC).getClientes().toStringClientesHistoricos();
                }
                
            }
            
            datosClientesHistoricos.setText(info);
            numeroHabitacion.setText("");
        } catch (NumberFormatException e) {
            datosClientesHistoricos.setText("Por favor, ingrese un valor válido.");
            numeroHabitacion.setText("");
        }
    }//GEN-LAST:event_mostrarClientesActionPerformed

    private void CheckOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckOutActionPerformed
        // TODO add your handling code here:
        String nombreC = nombreCheck.getText().trim();
        String apellidoC = apellidoCheck.getText().trim();
        String info;
        Cliente cliente;
        if (bookingHotel.getHashEstado().buscar(apellidoC, nombreC) == null) {
            info = """
                   El cliente buscado no se encuentra
                   hospedado en el Hotel.
                   """;
        } else {
            cliente = bookingHotel.getHashEstado().buscar(apellidoC, nombreC);
            int numeroHabitacionC = cliente.getNumeroHabitacion();
            ClienteHistorico clienteHistorico = new ClienteHistorico(-1, cliente.getNombre(), cliente.getApellido(), cliente.getEmail(), cliente.getGenero(), cliente.getLlegada(), numeroHabitacionC);
            bookingHotel.getArbolHabitaciones().buscarHabitacion(numeroHabitacionC).getClientes().insertarFinal(clienteHistorico);
            bookingHotel.getHashEstado().eliminar(apellidoC, nombreC);
            bookingHotel.getHabitacionesDisponibles().insertarFinal(numeroHabitacionC);
            info = "CheckOut realizado con éxito.";
        }
        datosCheckOut.setText(info);
        nombreCheck.setText("");
        apellidoCheck.setText("");
    }//GEN-LAST:event_CheckOutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CheckOut;
    private javax.swing.JTextField apellido;
    private javax.swing.JTextField apellidoCheck;
    private javax.swing.JButton buscarCliente;
    private javax.swing.JButton buscarReservacion;
    private javax.swing.JTextField cedula;
    private javax.swing.JTextField cedulaReservacion;
    private javax.swing.JButton checkIn;
    private javax.swing.JTextArea datosCheckIn;
    private javax.swing.JTextArea datosCheckOut;
    private javax.swing.JTextArea datosCliente;
    private javax.swing.JTextArea datosClientesHistoricos;
    private javax.swing.JTextArea datosReservacion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JButton mostrarClientes;
    private javax.swing.JTextField nombre;
    private javax.swing.JTextField nombreCheck;
    private javax.swing.JTextField numeroHabitacion;
    // End of variables declaration//GEN-END:variables
}
